---
modules-search: [ local, /usr/lib/calamares/modules ]

sequence:
  - show:
    - welcome
    - locale
    - keyboard
    - partition
    - users
    - summary
  - exec:
    - partition
    - mount
    - unpackfs
    - machineid
    - fstab
    - locale
    - keyboard
    - localecfg
    - users
    - networkcfg
    - hwclock
    - services-systemd
    - bootloader-config
    - grubcfg
    - bootloader
    - shellprocess
    - finished
  - show:
    - finished

branding: nexis

# Show "install" button on summary page, don't auto-start
prompt-install: true

# Don't run in a chroot-less environment
dont-chroot: false
