#!/bin/sh
# NeXiS Hypervisor — Alpine Linux first-boot package installer
# Runs once via the nexis-install OpenRC service on first boot.
# Installs QEMU/KVM, LXC, libvirt, Python stack, and the NeXiS daemon + web UI.
set -e
LOG=/var/log/nexis-install.log

_log() { printf '[%s] %s\n' "$(date '+%H:%M:%S')" "$1" | tee -a "$LOG"; }
_run() { "$@" >> "$LOG" 2>&1; }

_log "=== NeXiS Hypervisor Installation ==="
_log "Alpine Linux base detected — using apk"

# ── 1. System packages ────────────────────────────────────────────────────────

_log "Installing virtualisation and build dependencies…"
_run apk update
_run apk add --no-cache \
    qemu-system-x86_64 qemu-img \
    libvirt libvirt-daemon \
    lxc \
    novnc \
    python3 py3-pip py3-venv \
    py3-libvirt \
    nodejs npm \
    git curl jq \
    bridge-utils \
    nftables \
    openssh \
    ca-certificates \
    libvirt-dev \
    build-base \
    python3-dev \
    musl-dev \
    pkgconfig

# ── 2. Enable and start virtualisation ───────────────────────────────────────

_log "Enabling libvirt and networking services…"
_run rc-update add libvirtd default || true
_run rc-service libvirtd start      || true
_run rc-update add nftables default || true

# ── 3. Clone NeXiS Hypervisor ────────────────────────────────────────────────

INSTALL_DIR="/opt/nexis-hypervisor"
_log "Fetching NeXiS Hypervisor source…"
if [ -d "$INSTALL_DIR/.git" ]; then
    _run git -C "$INSTALL_DIR" pull --quiet
else
    _run git clone --quiet --depth 1 \
        https://github.com/santiagotoro2023/nexis-hypervisor \
        "$INSTALL_DIR"
fi

# ── 4. Python venv + daemon dependencies ─────────────────────────────────────

_log "Setting up Python environment…"
# Use --system-site-packages so py3-libvirt (from apk) is available
python3 -m venv --system-site-packages "$INSTALL_DIR/venv"
"$INSTALL_DIR/venv/bin/pip" install --quiet --upgrade pip
# Install daemon deps; libvirt-python will use the system py3-libvirt
"$INSTALL_DIR/venv/bin/pip" install --quiet \
    -r "$INSTALL_DIR/daemon/requirements.txt" \
    --ignore-installed libvirt-python || \
"$INSTALL_DIR/venv/bin/pip" install --quiet \
    -r "$INSTALL_DIR/daemon/requirements.txt"

# ── 5. Build web UI ──────────────────────────────────────────────────────────

_log "Building web interface…"
( cd "$INSTALL_DIR/web" && npm install --silent && npm run build --silent ) >> "$LOG" 2>&1

# ── 6. Data directory ─────────────────────────────────────────────────────────

_log "Creating data directory…"
mkdir -p /etc/nexis-hypervisor
chmod 700 /etc/nexis-hypervisor

# ── 7. TLS certificate (generated by daemon on first run) ────────────────────
# The daemon generates its own self-signed cert at startup — nothing to do here.

# ── 8. OpenRC service for the NeXiS daemon ───────────────────────────────────

_log "Installing NeXiS daemon OpenRC service…"
cat > /etc/init.d/nexis-hypervisor << 'SVC'
#!/sbin/openrc-run
name="nexis-hypervisor"
description="NeXiS Hypervisor daemon"
command="/opt/nexis-hypervisor/venv/bin/python3"
command_args="/opt/nexis-hypervisor/daemon/main.py"
command_background="yes"
pidfile="/run/nexis-hypervisor.pid"
output_log="/var/log/nexis-hypervisor.log"
error_log="/var/log/nexis-hypervisor.log"
directory="/opt/nexis-hypervisor/daemon"
environment="NEXIS_DATA=/etc/nexis-hypervisor NEXIS_PORT=8443"

depend() {
    need net libvirtd
    after libvirtd
}
SVC
chmod +x /etc/init.d/nexis-hypervisor
_run rc-update add nexis-hypervisor default

# ── 9. Firewall — allow port 8443 ────────────────────────────────────────────

_log "Opening port 8443 in nftables…"
cat > /etc/nftables.d/nexis.nft << 'NFT'
table inet nexis {
    chain input {
        type filter hook input priority 0;
        ct state established,related accept
        iifname lo accept
        tcp dport {22, 8443} accept
        drop
    }
}
NFT
_run rc-service nftables restart || true

# ── 10. NeXiS management shell ───────────────────────────────────────────────

_log "Installing NeXiS management shell..."

# Copy from source repo or ISO media
SHELL_SRC=""
for p in \
    /media/cdrom/nexis/nexis-shell.py \
    /media/usb/nexis/nexis-shell.py \
    /opt/nexis-hypervisor/iso/nexis-shell.py
do
    [ -f "$p" ] && { SHELL_SRC="$p"; break; }
done

if [ -n "$SHELL_SRC" ]; then
    cp "$SHELL_SRC" /usr/local/bin/nexis-shell
else
    curl -fsSL \
        https://raw.githubusercontent.com/santiagotoro2023/nexis-hypervisor/main/iso/nexis-shell.py \
        -o /usr/local/bin/nexis-shell >> "$LOG" 2>&1 || true
fi
chmod +x /usr/local/bin/nexis-shell
ln -sf /usr/local/bin/nexis-shell /usr/local/bin/nexis

# Auto-login root on tty1
grep -q '^tty1::' /etc/inittab 2>/dev/null && \
    sed -i 's|^tty1::.*|tty1::respawn:/sbin/getty -a root -L 0 tty1|' /etc/inittab

# Root profile: show nexis-shell on console, plain shell elsewhere
cat > /root/.profile << 'PROFILE'
export TERM=linux
alias nexis='/usr/local/bin/nexis-shell'
if [ "$(tty 2>/dev/null)" = "/dev/tty1" ] && [ -x /usr/local/bin/nexis-shell ]; then
    /usr/local/bin/nexis-shell
    printf '\n\033[38;5;208m  Returned to Linux shell. Type nexis to re-enter.\033[0m\n'
fi
PROFILE

_log "NeXiS shell installed"

# ── 11. Start daemon ──────────────────────────────────────────────────────────

_log "Starting NeXiS Hypervisor daemon…"
_run rc-service nexis-hypervisor start || true

IP=$(ip route get 1.1.1.1 2>/dev/null | grep -oP 'src \K\S+' || echo "?.?.?.?")
_log "=== Installation complete ==="
_log "Web UI: https://${IP}:8443"
_log "Default login: creator / Asdf1234!"

# Signal firstboot TUI to start (it has a dep on nexis-install)
touch /tmp/nexis-install-done
