---
# Copy the live squashfs to the target disk.
# The live-build squashfs is at this path when booted from the ISO.
unpack:
  - source: /run/live/medium/live/filesystem.squashfs
    sourcefs: squashfs
    destination: ""
