---
defaultGroups:
  - name: users
    system: true
  - name: libvirt
    system: true

# Allow setting root password
setRootPassword: true

# Don't require a regular user account (hypervisor = root-only)
doAutoLogin: false

# Defaults
userShell: /bin/bash

# Password validation
passwordRequirements:
  minLength: 8
  maxLength: -1
